/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary": "#ffffff",
          "on-tertiary-fixed": "#281900",
          "on-error": "#ffffff",
          "primary": "#031632",
          "on-surface-variant": "#44474d",
          "secondary": "#006b5f",
          "primary-fixed-dim": "#b6c7eb",
          "surface": "#f7f9fb",
          "error": "#ba1a1a",
          "surface-container-highest": "#e0e3e5",
          "on-secondary-fixed-variant": "#005047",
          "on-background": "#191c1e",
          "surface-dim": "#d8dadc",
          "surface-variant": "#e0e3e5",
          "on-primary-fixed": "#081b38",
          "on-surface": "#191c1e",
          "primary-container": "#1a2b48",
          "inverse-on-surface": "#eff1f3",
          "tertiary-fixed": "#ffdead",
          "primary-fixed": "#d7e2ff",
          "on-error-container": "#93000a",
          "surface-bright": "#f7f9fb",
          "tertiary-fixed-dim": "#e5c18a",
          "tertiary": "#211400",
          "on-primary-container": "#8293b5",
          "secondary-fixed": "#62fae3",
          "surface-container-low": "#f2f4f6",
          "background": "#f7f9fb",
          "outline-variant": "#c5c6ce",
          "inverse-surface": "#2d3133",
          "secondary-fixed-dim": "#3cddc7",
          "on-tertiary": "#ffffff",
          "on-tertiary-container": "#ad8d5b",
          "tertiary-container": "#3c2700",
          "outline": "#75777e",
          "on-secondary-fixed": "#00201c",
          "surface-container-lowest": "#ffffff",
          "on-secondary-container": "#007165",
          "surface-container-high": "#e6e8ea",
          "on-secondary": "#ffffff",
          "inverse-primary": "#b6c7eb",
          "secondary-container": "#62fae3",
          "surface-container": "#eceef0",
          "on-tertiary-fixed-variant": "#5b4217",
          "on-primary-fixed-variant": "#374765",
          "error-container": "#ffdad6",
          "surface-tint": "#4e5f7e"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Manrope", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"],
          "manrope": ["Manrope", "sans-serif"],
          "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
